- objetivos/antoniolm.md
Alumno : Antonio David López Machado
> Añadidos los objetivos de la semana

- objetivos/tonyESP.md
> Añado archivo objetivos

- Metodología_y_criterios_de_evaluación.md
- objetivos/JDSV.md
- proyecto/0.md
Además se modifica la cabecera del archivo Metodología_y_criterios_de_evaluación.md que no esta bien formada
> Actualizado hito 

- objetivos/ramongago.md
- proyecto/0.md
Se añaden los objetivos de la primera semana.
> Objetivos semana 01 RamonGago

- objetivos/erseco.md
https://github.com/JJ/CC-17-18/blob/master/objetivos/erseco.md
Alcanzados los objetivos de la segunda semana
https://github.com/erseco/CC-17-18/issues/1
> Entrega de fichero de objetivos

- README.md
- proyecto/1.md
- Creada descripción del proyecto en un fichero `index.md` en la rama `gh-pages` 
- Activado GitHub Pages.
https://github.com/erseco/ugr_cloud_computing/issues/2
https://github.com/erseco/ugr_cloud_computing/issues/3
https://github.com/erseco/ugr_cloud_computing/issues/4
> Entrega Hito 1

- objetivos/tonyESP.md
[Enlace](https://github.com/tonyESP/CC-17-18/blob/master/objetivos/tonyESP.md) a los objetivos correspondientes a este hito.
Actualización de objetivos.
> Actualización de objetivos.

- objetivos/antoniolm.md
https://github.com/JJ/CC-17-18/blob/master/objetivos/antoniolm.md
Se han actualizado los objetivos y se han corregido bug de estilo en el fichero .md
> Actualizados los objetivos

- objetivos/JDSV.md
- proyecto/1.md
https://github.com/JJ/CC-17-18/blob/master/objetivos/JDSV.md
Actualizado el fichero de objetivos de la segunda semana
> Añadidos objetivos segunda semana

- objetivos/ramongago.md
Se entrega la lista de objetivos de la semana 02 de RamonGago.
> Objetivos semana 02 RamonGago

- objetivos/daiaguirrei.md
Entrega de fichero de objetivos
> Objetivos segunda semana

- objetivos/carcedocarnero.md
Actualización de fichero de objetivos 
https://github.com/migadepan/CC-17-18/blob/master/objetivos/carcedocarnero.md
> Actualizo los objetivos de la semana

- objetivos/AKourts.md
Entrega de objetivos de la semana 2
> Objetivos de semana 2

- proyecto/1.md
https://github.com/migadepan/Master_CC
> Incluyo enlace a mi proyecto

- proyecto/1.md
https://github.com/JJ/CC-17-18/blob/master/objetivos/antoniolm.md
Entrega de mi proyecto del hito 1
https://github.com/Antoniolm/Master-CC/issues/1
https://github.com/Antoniolm/Master-CC/milestone/1
> Añadido proyecto al hito 1

- objetivos/agm-gr.md
- proyecto/1.md
https://github.com/AGM-GR/CC-17-18/blob/master/objetivos/agm-gr.md
Añadidos objetivos de Hito 1 y completado dicho hito, descripción del proyecto a realizar.
[Issue 1](https://github.com/AGM-GR/CloudComputing/issues/1)
[Issue 2](https://github.com/AGM-GR/CloudComputing/issues/2)
[Hito 0](https://github.com/AGM-GR/CloudComputing/milestone/1)
[Hito 1](https://github.com/AGM-GR/CloudComputing/milestone/2)
[Hito 2](https://github.com/AGM-GR/CloudComputing/milestone/3)
> Añadidos objetivos y proyecto

- proyecto/1.md
Completado el hito 1
https://github.com/jdanielsv/CC-UGR/milestone/1
https://github.com/jdanielsv/CC-UGR/issues/1
https://github.com/jdanielsv/CC-UGR/issues/2
https://github.com/jdanielsv/CC-UGR/issues/3
> Actualizado hito 1

- objetivos/javierfrereq.md
> añado objetivos semana 1

- objetivos/javierfrereq.md
- proyecto/0.md
> Actualizo  fichero 0.md

- objetivos/lchousal.md
- proyecto/0.md
Objetivos semana 2
<Enlaces a todo>
> Objetivos semana 2

- objetivos/javierfrereq.md
[X] He llevado a cabo las actividades correspondientes al objetivo y he entendido para qué sirve.
[X] He actualizado con la última versión del fichero de entrega y
>  Añado objetivo de la semana 2

- objetivos/antoniolm.md
https://github.com/JJ/CC-17-18/blob/master/objetivos/antoniolm.md
https://github.com/JJ/CC-17-18/blob/master/sesiones/03-semana.md
Añadidos los objetivos de la tercera semana y añadidos los ejercicios del tema 1
> Añadidos objetivos de la semana

- proyecto/1.md
https://github.com/JJ/CC-17-18/blob/master/proyecto/1.md
anterior, he aumentado en uno el número de versión en su columna correspondiente. 
https://github.com/daiaguirre979/ProyectoMasterCC/issues/1
https://github.com/daiaguirre979/ProyectoMasterCC/issues/2
https://github.com/daiaguirre979/ProyectoMasterCC/issues/3
https://daiaguirre979.github.io/ProyectoMasterCC/
> Entrega Hito1

- objetivos/erseco.md
- objetivos/javierfrereq.md
https://github.com/erseco/CC-17-18/blob/master/objetivos/erseco.md
Actualizado fichero de objetivos con los de la tercera semana
> Entrega de fichero de objetivos 

- objetivos/JDSV.md
Añadidos los ejercicios del tema 1 y actualizado los objetivos con los de la tercera semana
> Añadidos los ejercicios y objetivos

- objetivos/tonyESP.md
Entrega de los objetivos con [ci skip]
<Enlaces a todo>
> [ci skip] Añade objetivos

- proyecto/1.md
https://github.com/javierfrereq/CC-17-18/blob/master/proyecto/1.md
Entrega del Hito 1
<Enlaces a todo>
https://github.com/javierfrereq/MII_CC_Proyecto/issues/1
https://github.com/javierfrereq/MII_CC_Proyecto/issues/2
https://github.com/javierfrereq/MII_CC_Proyecto/issues/3
https://javierfrereq.github.io/MII_CC_Proyecto/
> Entrego fichero 1.md

- proyecto/1.md
Corresponde al [Hito 1](https://github.com/RamonGago/Cloud-Computing_Project/milestone/1)
Se añade el Hito 1 de RamonGago.
Se han cerrado los siguientes issues, pertenecientes al milestone [Hito 1](https://github.com/RamonGago/Cloud-Computing_Project/milestone/1?closed=1):
- [#1](https://github.com/RamonGago/Cloud-Computing_Project/issues/1)
- [#2](https://github.com/RamonGago/Cloud-Computing_Project/issues/2)
- [#3](https://github.com/RamonGago/Cloud-Computing_Project/issues/3)
- [#5](https://github.com/RamonGago/Cloud-Computing_Project/issues/5)
> Added Hito 1

- objetivos/ramongago.md
Se entrega la lista de objetivos de la semana 03 de RamonGago.
> Updated Objectives Week 3

- objetivos/AKourts.md
- proyecto/1.md
https://github.com/AKourts/CC-17-18/blob/master/objetivos/AKourts.md
Objectives of 3rd week
> objectives of 3rd week

- objetivos/JDSV.md
Actualizado el archivo de objetivos con la tercera semana.
> Actualizado objetivos de la semana

- objetivos/erseco.md
https://github.com/erseco/CC-17-18/blob/master/objetivos/erseco.md
Actualizados los objetivos de la semana 4
> Añadidos objetivos semana 3 (erseco.md)

- objetivos/lchousal.md
actualizacion de los objetivos
> Añadidos objetivos semana 3

- objetivos/carcedocarnero.md
Actualización de los objetivos
> actualizo objetivos

- objetivos/agm-gr.md
[https://github.com/AGM-GR/CC-17-18/blob/master/objetivos/agm-gr.md](https://github.com/AGM-GR/CC-17-18/blob/master/objetivos/agm-gr.md)
Se han actualizado los objetivos de la semana pasada y de esta semana.
> Actualizados objetivos semanas 3 y 4

- objetivos/tonyESP.md
Entrega de los objetivos de la semana 4
> Añade objetivos semana 4 Tony

- objetivos/javierfrereq.md
> Actualizo semana 3

- objetivos/carcedocarnero.md
- proyecto/1.md
> Objetivos actualizados semana 4

- objetivos/javierfrereq.md
> Actualizo semana 4

- objetivos/JDSV.md
Entrega de los objetivos resueltos de la 4ª semana.
> Añadidos objetivos semana 4

- objetivos/ramongago.md
Se entrega la lista de objetivos completados de la semana 04 de RamonGago.
> Updated objectives week 04

- proyecto/2.md
- Generado aprovisionamiento con *ansible*, 
- Configurado *travis*, 
- Actualizada documentación
https://github.com/erseco/ugr_cloud_computing/issues/5
https://github.com/erseco/ugr_cloud_computing/issues/6
https://github.com/erseco/ugr_cloud_computing/issues/7
https://github.com/erseco/ugr_cloud_computing/issues/8
> Entrega Hito 2

- objetivos/JDSV.md
Actualización de fichero de objetivos. Se han añadidos todas las semanas pero solamente completada hasta la 5.
> Actualizados objetivos

- objetivos/AKourts.md
<https://github.com/JJ/CC-17-18/blob/master/objetivos/AKourts.md>
* [X ] He llevado a cabo las actividades correspondientes al objetivo y he entendido para qué sirve.
* [X ] He actualizado con la última versión del fichero de entrega y
Añadidos los objetivos para la semana 4
> objetivos semana 4

- objetivos/erseco.md
https://github.com/erseco/CC-17-18/blob/master/objetivos/erseco.md
Actualizados los objetivos de la semana 5
> Añadidos objetivos semana 5 (erseco.md)

- proyecto/2.md
correspondiente.   
Se ha realizado la entrega del hito 2
https://github.com/Antoniolm/Master-CC/issues/5
https://github.com/Antoniolm/Master-CC/issues/4
> Realizado el hito 2

- objetivos/daiaguirrei.md
* [x ] He llevado a cabo las actividades correspondientes al objetivo y he entendido para qué sirve.
> Objetivos semana

- proyecto/2.md
* [ x ] He leído el guión del hito
* [ x ] Cumplo los prerrequisitos (he aprobado el hito anterior, por ejemplo)
* [ x ] He actualizado con la última versión del fichero de entrega y
* [ x ] Si estoy enviando otra versión porque no pasó los tests la
He completado el hito 2 añadiendo al repositorio en la rama master los archivos para el aprovisionamiento del sistema con ansible.
https://github.com/AGM-GR/CloudComputing/milestone/4
https://github.com/AGM-GR/CloudComputing/issues/3
> Terminado hito2

- proyecto/2.md
Entrega del hito 2
https://github.com/jdanielsv/CC-UGR/milestone/2
https://github.com/jdanielsv/CC-UGR/issues/4
https://github.com/jdanielsv/CC-UGR/issues/5
https://github.com/jdanielsv/CC-UGR/issues/6
> Terminado el hito 2

- objetivos/JDSV.md
- proyecto/2.md
Se ha verificado que el aprovisionamiento de Antoniolm funciona correctamente.
> Actualizado el archivo de objetivos con la verificación de provisionamiento.

- objetivos/antoniolm.md
- proyecto/2.md
https://github.com/JJ/CC-17-18/blob/master/objetivos/antoniolm.md
Verificación del provisionamiento de erseco
> Verificado el repositorio de erseco

- proyecto/2.md
https://github.com/JJ/CC-17-18/blob/master/objetivos/erseco.md
Revisado el aprovisionamiento de @AGM-GR en AWS con ansible
> Revisado el hito2 de @AGM-GR

- objetivos/tonyESP.md
Añadidos los objetivos para la semana 5 y 6.
> Entrega objetivos

- objetivos/carcedocarnero.md
- proyecto/2.md
> Actualización de objetivos

- proyecto/2.md
Enlace con mi proyecto, contiene los archivos de provision
https://github.com/migadepan/Master_CC
> Añadido hito 2

- objetivos/tonyESP.md
- proyecto/2.md
Verificación del provisionamiento de @carcedocarnero en aws con chef
> Revision del hito2 de @carcedocarnero

- proyecto/2.md
Entrega del hito del proyecto de Cloud Computing
* [x ] Cumplo los prerrequisitos (he aprobado el hito anterior, por ejemplo)
* [x ] Si estoy enviando otra versión porque no pasó los tests la
correspondiente.
> Agregando link proyecto

- proyecto/2.md
He probado la receta de mi compañero, funciona correctamente, la captura de pantalla se encuentra en el readme del hito2 de mi proyecto.
https://github.com/migadepan/Master_CC/tree/master/provision/chef-solo
> Comprobada práctica de compañero

- objetivos/daiaguirrei.md
- proyecto/2.md
https://github.com/daiaguirre979/CloudComputing/blob/master/objetivos/daiaguirrei.md
> Modificacion objetivos

- objetivos/AKourts.md
- proyecto/2.md
https://github.com/AKourts/CC-17-18/blob/master/objetivos/AKourts.md
Update the objectives of this week and check the provision code of @lchousal with ansible
> Update the objectives of this week and check the provision code of @lchousal

- objetivos/javierfrereq.md
> Actualización de semana 5 y 6

- objetivos/lchousal.md
- proyecto/2.md
https://github.com/lchousal/CC-17-18/blob/master/objetivos/lchousal.md
Comprobar que el provisionamiento de AKourt funciona correctamente
> Comprobacion provisionamiento AKourts

- proyecto/2.md
https://github.com/javierfrereq/CC-17-18/blob/master/proyecto/2.md
Entrega de Hito 2
<Enlaces a todo>
https://github.com/javierfrereq/MII_CC_Proyecto/issues/4
https://github.com/javierfrereq/MII_CC_Proyecto/issues/5
https://github.com/javierfrereq/MII_CC_Proyecto/issues/6
https://javierfrereq.github.io/MII_CC_Proyecto/
> actualizar 2.md

- objetivos/javierfrereq.md
- proyecto/2.md
> Revision de Hito 2 @tonyesp

- proyecto/2.md
Se añade el Hito 2 de RamonGago.
Se han cerrado los siguientes issues, pertenecientes al milestone [Hito 2](https://github.com/RamonGago/Cloud-Computing_Project/milestone/2):
- [#6](https://github.com/RamonGago/Cloud-Computing_Project/issues/6)
- [#7](https://github.com/RamonGago/Cloud-Computing_Project/issues/7)
> Updated Hito 2 and classmate provisioning test (@Akourts)

- objetivos/ramongago.md
- proyecto/2.md
Se entrega la lista de objetivos completados de la semanas 05 y 06 de RamonGago. También se adjuntan los objetivos futuros de las semanas 07 y 08, pero sin marcar todavía.
> Added objectives weeks 05 and 06

- objetivos/agm-gr.md
- proyecto/2.md
(https://github.com/JJ/CC-17-18/blob/master/objetivos/agm-gr.md)[https://github.com/JJ/CC-17-18/blob/master/objetivos/agm-gr.md]
Añadidos los objetivos de la semana 5 y comprobado el aprovisionamiento de ramongago.
> Actualización de objetivos y comprobación de aprovisionamiento

- proyecto/2.md
correspondiente.
Actualizada documentacion y README.md
> Actualizacion Hito 2

- proyecto/2.md
Actualizada la documentación del proyecto
> Actualizada documentación

- proyecto/2.md
Mejorada la descripción del sitio web del proyecto y de su README principal.
https://github.com/Antoniolm/Master-CC/issues/6
https://github.com/Antoniolm/Master-CC/issues/7
https://github.com/Antoniolm/Master-CC/issues/8
> Mejorada la descripción del proyecto

- proyecto/2.md
Corresponde al hito **2**
[Objetivos Hito 2](https://github.com/tonyESP/CC-17-18/blob/master/objetivos/tonyESP.md)
Corrección de: 
> -2 por favor, explica un poco de qué va el proyecto, qué es lo que has instalado, por qué... El formato del README.md es incorrecto
[Enlace al proyecto](https://github.com/tonyESP/MII_CC_Proyecto)
[Enlace a la web "gh-pages"](https://tonyesp.github.io/MII_CC_Proyecto/)
[Enlace a la descripción de la entrega del hito 2](https://github.com/tonyESP/MII_CC_Proyecto/blob/master/provision/chef-solo/README.md) (*1*)
(1) Efectivamente, no indique que este fichero existía. Para próximas entregas tendré en cuenta que debo …
> Re-Entrega del HITO 2

- proyecto/2.md
Agregando una breve detale sobre lo que va el proyecto.
> Modificando readme del proyecto

- proyecto/2.md
https://github.com/AKourts/CC-17-18/blob/master/objetivos/AKourts.md 
Fix conflict of file 2.md
> Fix conflict of file 2.md

- proyecto/2.md
Corresponde al [Hito 2](https://github.com/RamonGago/Cloud-Computing_Project/milestone/2)
Se añade el Hito 2 de RamonGago.
Se han cerrado los siguientes issues, pertenecientes al milestone [Hito 2](https://github.com/RamonGago/Cloud-Computing_Project/milestone/2?closed=1):
- [#4](https://github.com/RamonGago/Cloud-Computing_Project/issues/4)
- [#6](https://github.com/RamonGago/Cloud-Computing_Project/issues/6)
- [#7](https://github.com/RamonGago/Cloud-Computing_Project/issues/7)
> Fix conflict - Update Hito 2

- proyecto/2.md
Se ha realizado la corrección de la documentación de la página principal del proyecto y de la página web.
> Corrección hito2 archivos readme

- proyecto/2.md
https://github.com/lchousal/CC-17-18/blob/master/objetivos/lchousal.md
Corrección de la documentación del proyecto
https://github.com/lchousal/CC-proyecto/issues/5
> Corrección hito 2

- objetivos/JDSV.md
- proyecto/2.md
Se ha actualizado el aprovisionamiento del sistema eliminando docker. 
https://github.com/jdanielsv/CC-UGR/issues/8
https://github.com/jdanielsv/CC-UGR/issues/7
> Actualización del aprovisionamiento

- proyecto/3.md
Agregado hito 3
https://github.com/erseco/ugr_cloud_computing/issues/9
> update milestone 3

- objetivos/tonyESP.md
[Fichero objetivos TonyESP](https://github.com/tonyESP/CC-17-18/blob/master/objetivos/tonyESP.md)
Actualizar fichero objetivos.
> actualizo objetivos sema 8

- objetivos/javierfrereq.md
[Enlace](https://github.com/javierfrereq/CC-17-18/blob/master/objetivos/javierfrereq.md)
Actualizar objetivos
> Actualizar Objetivos 

- objetivos/agm-gr.md
[Objetivos AGM-GR](https://github.com/JJ/CC-17-18/blob/master/objetivos/agm-gr.md)
He actualizado el fichero de objetivos, con los objetivos de las semanas 6,7 y 8
> Actulización objetivos semana 8

- proyecto/3.md
Se ha añadido toda la información y ficheros referentes al hito 3 de la asignatura
https://github.com/Antoniolm/Master-CC/issues/9
https://github.com/Antoniolm/Master-CC/issues/10
> Añadido hito 3

- proyecto/3.md
Se ha añadido el hito 3, en mi repositorio he creado el scrip acopio.sh el cual crea una máquina en azure y la provisiona automáticamente. Se ha actualizado toda la documentación correspondiente.
[https://github.com/AGM-GR/CloudComputing/milestone/5](https://github.com/AGM-GR/CloudComputing/milestone/5)
[https://github.com/AGM-GR/CloudComputing/issues/4](https://github.com/AGM-GR/CloudComputing/issues/4)
> Actualizado hito 3

- proyecto/3.md
He comprobado el script "Acopio" de antoniolm. 
Resultado de ejecución del escript:
> Comprobado acopio de Antonio

- proyecto/3.md
<enlace a los objetivos correspondientes a este hito>
Verificación del hito 3 de AGM-GR
> Verificado hito 3 de AGM-GR

- objetivos/AKourts.md
https://github.com/AKourts/CC-17-18/blob/master/objetivos/AKourts.md 
Update objectives
> Update Objectives file

- proyecto/3.md
Entrega del hito 3.
Se ha automatizado la creación de la máquina virtual en azure.
El repositorio en el siguiente [enlace](https://github.com/tonyESP/MII_CC_Proyecto).
Documentación del despliegue en el [enlace]( https://github.com/tonyESP/MII_CC_Proyecto/blob/master/automatizacion/README.md).
Web del proyecto en el siguiente [enlace]( https://tonyesp.github.io/MII_CC_Proyecto/).
[Crear acopio.sh](https://github.com/tonyESP/MII_CC_Proyecto/issues/11)
[Llevarse bien con AZURE CLI y no morir en el intento. ](https://github.com/tonyESP/MII_CC_Proyecto/issues/12)
[Entregar hito …
> Entrega del Hito 3

- proyecto/3.md
Crear una máquina virtual con Azure Cli.
[Enlace proyecto](https://github.com/daiaguirre979/ProyectoMasterCC/blob/master/LICENSE)
[Enlace Readme Azure Cli](https://github.com/daiaguirre979/ProyectoMasterCC/blob/master/LICENSE)
[Issue Creación máquina virtual](https://github.com/daiaguirre979/ProyectoMasterCC/issues/10)
[Issue Configuración de AzureCli](https://github.com/daiaguirre979/ProyectoMasterCC/issues/11)
[Issue Ejecución provisionamiento](https://github.com/daiaguirre979/ProyectoMasterCC/issues/12)
> Finalizando Hito3

- objetivos/daiaguirrei.md
https://github.com/daiaguirre979/CloudComputing/blob/master/objetivos/daiaguirrei.md
> Objetivos de la octava semana

- proyecto/3.md
Verificación del hito 3 de @AKourts
> Reviso Hito3 de @AKourts

- proyecto/3.md
Descripción de los pasos realizados para el hito 3, automatización de la creación y provisionamiento de la MV
https://github.com/migadepan/Master_CC
> Enlace al hito 3

- proyecto/3.md
Comprobación despliegue @daiaguirre979
> Update 3.md comprobacion @daiaguirre979 

- proyecto/3.md
Entrega del hito 3.
Automatización para la creación de la máquina virtual en Azure.
El repositorio del Micro Servicios [enlace](https://github.com/javierfrereq/MII_CC_Proyecto_MicroServicios).
Documentación de Automatización [enlace]( https://github.com/javierfrereq/MII_CC_Proyecto_MicroServicios/blob/master/automatizacion/README.md).
La Web del proyecto [enlace]( https://javierfrereq.github.io/MII_CC_Proyecto_MicroServicios/).
[Leer el guion del Hito 3](https://github.com/javierfrereq/MII_CC_Proyecto_MicroServicios/issues/1)
[Crear el Archivo SSH](https://github.com/javierfrereq/MII_CC_Proyecto_MicroServicios/issues/2) …
> Modificar el 3.md

- objetivos/lchousal.md
Actualización del fichero de objetivos
> actualización objetivos semana 8

- proyecto/3.md
Corrección de los errores cometido en el hito 3 
https://github.com/Antoniolm/Master-CC/issues/11
> Corrección hito 3

- proyecto/3.md
**Hay que enviar de forma diferenciada los objetivos y el hito y
borrar la parte que no corresponda** 
correspondiente.   
Corrección de la instalación de ansible. 
https://github.com/Antoniolm/Master-CC/issues/12
> Correción instalación ansible

- proyecto/3.md
[Enlace a los objetivos](https://github.com/tonyESP/CC-17-18/blob/master/objetivos/tonyESP.md)
correspondiente.   
He justificado la elección de una imagen determinada. 
[Enlace al proyecto](https://github.com/tonyESP/Project_CC)
[Enlace al issue](https://github.com/tonyESP/MII_CC_Proyecto/issues/14)
> ReEntrega Hito 3

- proyecto/3.md
Corresponde al [Hito 3](https://github.com/RamonGago/Cloud-Computing_Project/milestone/3)
Se añade el Hito 3 de RamonGago.
Se han cerrado los siguientes issues, pertenecientes al milestone [Hito 3](https://github.com/RamonGago/Cloud-Computing_Project/milestone/3?closed=1):
- [#8](https://github.com/RamonGago/Cloud-Computing_Project/issues/8)
- [#9](https://github.com/RamonGago/Cloud-Computing_Project/issues/9)
- [#10](https://github.com/RamonGago/Cloud-Computing_Project/issues/10)
> Added Hito 3

- proyecto/3.md
Verificar el acopio.sh de Lchousal
> Verficación proyecto

- proyecto/3.md
He modificado lo correspondiente a la corrección del hito 3 y los comandos de instalación con pip
[https://github.com/AGM-GR/CloudComputing/issues/4](https://github.com/AGM-GR/CloudComputing/issues/4)
[https://github.com/AGM-GR/CloudComputing/milestone/5](https://github.com/AGM-GR/CloudComputing/milestone/5)
> Modificado hito 3

- proyecto/3.md
[enlace Hito 3](https://github.com/javierfrereq/CC-17-18/blob/master/proyecto/3.md)
[enlace objetivos](https://github.com/javierfrereq/CC-17-18/blob/master/objetivos/javierfrereq.md)
* [ X ] He leído el guión del hito
* [ X ] Cumplo los prerrequisitos (he aprobado el hito anterior, por ejemplo)
* [ X ] He actualizado con la última versión del fichero de entrega y
* [ X ] Si estoy enviando otra versión porque no pasó los tests la
* Se procedió a corregir la página web del proyecto agregando el porque de UbuntuLTS 
[Enlace del proyecto](https://javierfrereq.github.io/MII_CC_Proyecto_MicroServicios/)
[Enlace del …
> Modifico el Hito 3

- proyecto/3.md
[enlace Hito 3](https://github.com/javierfrereq/CC-17-18/blob/master/proyecto/3.md)
[enlace objetivos](https://github.com/javierfrereq/CC-17-18/blob/master/objetivos/javierfrereq.md)
* [ X ] He leído el guión del hito
* [ X ] Cumplo los prerrequisitos (he aprobado el hito anterior, por ejemplo)
* [ X ] He actualizado con la última versión del fichero de entrega y
* Se procedio a verificar el hito 3 de @tonyESP
[Enlace del proyecto](https://javierfrereq.github.io/MII_CC_Proyecto_MicroServicios/)
> verificar proyecto de TonyESP

- objetivos/ramongago.md
Se entrega la lista de objetivos completados de las semanas 07 y 08 de RamonGago.
> Updated objectives Weeks 07 and 08

- proyecto/4.md
Primera prueba de travis para el hito 4
> Prueba travis - Orquestación

- proyecto/4.md
Segunda prueba de travis para el hito 4
> Segunda prueba de travis

- objetivos/antoniolm.md
https://github.com/JJ/CC-17-18/blob/master/sesiones/09-semana.md
https://github.com/JJ/CC-17-18/blob/master/sesiones/10-semana.md
Actualización de los objetivos
> Actualización de los objetivos

- proyecto/4.md
Corresponde al hito <4>
Instalación de vagrant y creación de mv
[Proyecto](https://github.com/daiaguirre979/ProyectoMasterCC)
[issue 1](https://github.com/daiaguirre979/ProyectoMasterCC/issues/13)
[issue 2](https://github.com/daiaguirre979/ProyectoMasterCC/issues/14)
[issue 3](https://github.com/daiaguirre979/ProyectoMasterCC/issues/15)
> Terminando hito4

- objetivos/agm-gr.md
[https://github.com/JJ/CC-17-18/blob/master/objetivos/agm-gr.md](https://github.com/JJ/CC-17-18/blob/master/objetivos/agm-gr.md)
Actualizado el fichero de objetivos semanales con la semana 10 y 11
> Actualizados los objetivos semanales

- objetivos/javierfrereq.md
[enlace](https://github.com/javierfrereq/CC-17-18/blob/master/objetivos/javierfrereq.md)
[X] He llevado a cabo las actividades correspondientes al objetivo y he entendido para qué sirve.
[X] He actualizado con la última versión del fichero de entrega y
> Añado objetivos semana 9 y 10

- proyecto/4.md
[Fichero objetivos](https://github.com/tonyESP/CC-17-18/blob/master/objetivos/tonyESP.md)
Para orquestar las maquinas necesarias para este proyecto se ha utilizado vagrant en su version "2.0.1". Se ha elegido esta herramienta por su sencillez y compativilidad con azure.
Tanto el sistema operativo como el aprovisionamiento es el utilizado en las versiones anteriores. Podemos ver una guia de instalacion en el siguiente [enlace](https://github.com/tonyESP/MII_CC_Proyecto/tree/master/orquestacion).
[Proyecto](https://github.com/tonyESP/MII_CC_Proyecto)
[Orquestación](https://github.com/tonyESP/MII_CC_Proyecto/tree/master/orquestac …
> Entrega del Hito 4

- proyecto/4.md
Chequeo del hito 4 de Alejandro Guerrero Martinez
>  chequeo de hito de AGM-GR

- proyecto/4.md
Comprobación de la orquestación de tonyESP
> Comprobación de tonyESP

- proyecto/4.md
Hito 4 del proyecto, ampliación del readme principal y enlace al readme concreto de orquestación
https://github.com/migadepan/Master_CC
> enlace al hito 4 del proyecto

- proyecto/4.md
Revisión del hito 4 a Antoniolm
> Revisado hito 4 de Antoniolm

- proyecto/4.md
Comprobación de la orquestación de @migadepan
> Comprobación hito 4 @migadepan

- proyecto/4.md
Entrega hito 4
https://github.com/jdanielsv/CC-UGR/issues/12
https://github.com/jdanielsv/CC-UGR/issues/11
https://github.com/jdanielsv/CC-UGR/milestone/4
> Actualizado con el hito 4

- proyecto/4.md
https://github.com/lchousal/CC-17-18/blob/master/objetivos/lchousal.md
Entrega del hito 4
https://github.com/lchousal/CC-proyecto/issues/14
https://github.com/lchousal/CC-proyecto/issues/13
> Entrega hito 4

- proyecto/4.md
Corresponde al [Hito 4](https://github.com/RamonGago/Cloud-Computing_Project/milestone/4)
Se añade el Hito 4 de RamonGago.
Se han cerrado los siguientes issues, pertenecientes al milestone [Hito 4](https://github.com/RamonGago/Cloud-Computing_Project/milestone/4?closed=1):
- [#11](https://github.com/RamonGago/Cloud-Computing_Project/issues/11)
- [#12](https://github.com/RamonGago/Cloud-Computing_Project/issues/12)
> Added Hito 4 - Ramon Gago

- proyecto/4.md
He realizado la verificación del hito 4 de AKourts
> Verificación hito

- proyecto/4.md
Update link in README
https://github.com/AKourts/Project_CC
> Update link in README

- proyecto/4.md
Corrección del hito 4, elección de sistemas operativos != de ubuntu, provisionamiento mediante chef incluido en vagrant, vagrantfile sin repetición de constantes.
https://github.com/tonyESP/MII_CC_Proyecto
https://github.com/tonyESP/MII_CC_Proyecto/tree/master/orquestacion
> ReEntrega hito 4

- proyecto/4.md
Corresponde al Hito 4
[Enlace Objetivos](https://github.com/javierfrereq/CC-17-18/blob/master/objetivos/javierfrereq.md)
Orquestación de máquinas virtuales 
Documentación de instalación: [enlace](https://github.com/javierfrereq/MII_CC_Proyecto_MicroServicios/tree/master/orquestacion).
[Proyecto](https://github.com/javierfrereq/MII_CC_Proyecto_MicroServicios)
[Orquestación](https://github.com/javierfrereq/MII_CC_Proyecto_MicroServicios/tree/master/orquestacion)
> Reenviar Hito

- proyecto/4.md
Corresponde al hito <4>
He modificado la versión de Vagrant -azureCli
[Orquestacion](https://github.com/daiaguirre979/ProyectoMasterCC/tree/master/orquestacion)
> Modificando hito4

- proyecto/4.md
Revise and Correct Vagrantfile
https://github.com/AKourts/Project_CC
https://github.com/AKourts/Project_CC/blob/master/orquestacion/Vagrantfile
https://github.com/AKourts/Project_CC/issues/9
> Revise and correct Vagrantfile

- proyecto/2.md
- proyecto/4.md
Corrección del archivo de orquestación Vagratfile y actualización de los readme.
> Corrección errores hito 4

- objetivos/erseco.md
https://github.com/erseco/CC-17-18/blob/master/objetivos/erseco.md
Actualizado el fichero de objectivos
> Updated goals file

- proyecto/5.md
Realizado el 5º hito de la asignatura, para hacerlo más cómodo se ha creado un `Vagrantfile`que crea la instancia en `AWS`, provisiona con `ansible` y luego ejecuta la imagen docker que descarga desde `docker hub`, dicha imagen se ha creado con el `Dockerfile` del mismo directorio
https://github.com/erseco/ugr_cloud_computing/issues/13
> Added 5th milestone

- objetivos/javierfrereq.md
[enlace](https://github.com/javierfrereq/CC-17-18/blob/master/objetivos/javierfrereq.md)
[X] He llevado a cabo las actividades correspondientes al objetivo y he entendido para qué sirve.
[X] He actualizado con la última versión del fichero de entrega y
> Actualizar objetivos

- objetivos/agm-gr.md
[https://github.com/AGM-GR/CC-17-18/blob/master/objetivos/agm-gr.md](https://github.com/AGM-GR/CC-17-18/blob/master/objetivos/agm-gr.md)
Añadidos los objetivos de la semana 12.
> Actualizados objetivos semana 12

- proyecto/5.md
Corresponde al Hito 5
[Enlace Objetivos](https://github.com/javierfrereq/CC-17-18/blob/master/objetivos/javierfrereq.md)
Despliegue de un contenedor 
Documentación de instalación: [enlace](https://github.com/javierfrereq/MII_CC_Proyecto_MicroServicios/tree/master/contenedores).
[Proyecto](https://github.com/javierfrereq/MII_CC_Proyecto_MicroServicios)
[Contenedores](https://github.com/javierfrereq/MII_CC_Proyecto_MicroServicios/tree/master/contenedores)
[Entrega de Objetivos](https://github.com/javierfrereq/MII_CC_Proyecto_MicroServicios/issues/8)
[Aprender docker](https://github.com/javierfrereq/MII_CC_Proyecto_MicroServicios/issues/9)
[Entregar …
> Modificar 5.md

- proyecto/5.md
Entrega del hito 5. Contenedor en dockerhub, SO:Debian, php, php-mysql, apache.
https://github.com/tonyESP/MII_CC_Proyecto/milestone/5
https://github.com/tonyESP/MII_CC_Proyecto/issues/18
https://github.com/tonyESP/MII_CC_Proyecto/issues/19
https://github.com/tonyESP/MII_CC_Proyecto/issues/20
[Enlace a la descripcion de los contenedores utilizados](https://github.com/tonyESP/MII_CC_Proyecto/blob/master/contenedores/README.md)
> Entrega hito 5

- proyecto/5.md
Entrega del hito 5, desarrollo de una API sencilla y despliegue del sistema con Docker.
[https://github.com/AGM-GR/CloudComputing/milestone/7](https://github.com/AGM-GR/CloudComputing/milestone/7)
[https://github.com/AGM-GR/CloudComputing/issues/6](https://github.com/AGM-GR/CloudComputing/issues/6)
[https://github.com/AGM-GR/CloudComputing/issues/7](https://github.com/AGM-GR/CloudComputing/issues/7)
> Añadido hito 5

- proyecto/5.md
Uso de contenedores Docker
[Proyecto](https://github.com/daiaguirre979/ProyectoMasterCC)
[Crear Dockerfile](https://github.com/daiaguirre979/ProyectoMasterCC/issues/16)
[Instalar Docker](https://github.com/daiaguirre979/ProyectoMasterCC/issues/17)
[Crear cuenta dockerhub](https://github.com/daiaguirre979/ProyectoMasterCC/issues/18)
[Crear Readme](https://github.com/daiaguirre979/ProyectoMasterCC/issues/19)
[Modificar Readme](https://github.com/daiaguirre979/ProyectoMasterCC/issues/20)
> Entrega hito5

- proyecto/5.md
Entrega del hito 5, creación de cuenta en Docker, vinculación de mi proyecto GitHub, creación del documento Dockerfile, ejecución de los comandos necesarios para levantar el servicio.
https://github.com/migadepan/Master_CC/
> Entrega de hito 5

- proyecto/5.md
Corresponde al [Hito 5](https://github.com/RamonGago/Cloud-Computing_Project/milestone/5)
Se añade el Hito 5 de RamonGago.
Se han cerrado los siguientes issues, pertenecientes al milestone [Hito 5](https://github.com/RamonGago/Cloud-Computing_Project/milestone/5?closed=1):
- [#13](https://github.com/RamonGago/Cloud-Computing_Project/issues/13)
- [#14](https://github.com/RamonGago/Cloud-Computing_Project/issues/14)
- [#15](https://github.com/RamonGago/Cloud-Computing_Project/issues/15)
> Added Hito 5

- objetivos/ramongago.md
[ramongago.md](https://github.com/JJ/CC-17-18/blob/master/objetivos/ramongago.md)
Se actualizan los objetivos de @ramongago hasta la fecha
> Updated objectives

- objetivos/stiago.md
- proyecto/0.md
- proyecto/1.md
- proyecto/2.md
- proyecto/3.md
- proyecto/4.md
- proyecto/5.md
Corresponde al hito 0, 1,  2,  3, 4 y 5
y 
[Fichero objetivos](https://github.com/STiago/CC-17-18/blob/master/objetivos/stiago.md)
Entrega del proyecto y objetivos
[Hito 0](https://github.com/STiago/Lecrin_Bot/milestone/1)
[Hito 1](https://github.com/STiago/Lecrin_Bot/milestone/2)
[Hito 2](https://github.com/STiago/Lecrin_Bot/milestone/3)
[Hito 3](https://github.com/STiago/Lecrin_Bot/milestone/4)
[Hito 4](https://github.com/STiago/Lecrin_Bot/milestone/5)
[Hito 5](https://github.com/STiago/Lecrin_Bot/milestone/6)
> Añadiendo Hito y fichero de objetivos

- proyecto/6.md
Entrega del hito final de la asignatura
https://github.com/Antoniolm/Master-CC/issues/19
> Entrega del hito 6

- objetivos/daiaguirrei.md
[Objetivos](https://github.com/JJ/CC-17-18/blob/master/objetivos/daiaguirrei.md)
[Ejercicio de contenedores](https://github.com/daiaguirre979/CC-Master/blob/master/Ejercicios/contenedores.md)
[Ejercicios](https://github.com/daiaguirre979/CC-Master/blob/master/Ejercicios) 
> Actualizando Objetivos

- objetivos/carcedocarnero.md
https://github.com/migadepan/CC-17-18/blob/master/objetivos/carcedocarnero.md
Actualización del fichero objetivos con los objetivos de las últimas semanas
https://github.com/migadepan/CC-17-18/blob/master/objetivos/carcedocarnero.md
> Actualización de los últimos objetivos

- proyecto/6.md
Documentos correspondientes al hito 6, uso de Docker-compose
https://github.com/migadepan/Master_CC/milestone/7?closed=1
https://github.com/migadepan/Master_CC/tree/master/compose
> Entrega de hito 6

- proyecto/6.md
Corresponde al hito6
* [X ] He actualizado con la última versión del fichero de entrega y
Composición de contenedores.
[issues](https://github.com/daiaguirre979/ProyectoMasterCC/milestone/7?closed=1)
[Enlace al repositorio](https://github.com/daiaguirre979/ProyectoMasterCC/tree/master/composicion)
[Readme](https://github.com/daiaguirre979/ProyectoMasterCC)
[Ejercicios](https://github.com/daiaguirre979/CC-Master/tree/master/Ejercicios)
> Hito 6 - Entrega

- proyecto/6.md
Entrega del hito 6 con 3 servicios: cliente, servidor y de base de datos
https://github.com/jdanielsv/CC-UGR/issues/22
https://github.com/jdanielsv/CC-UGR/issues/21
https://github.com/jdanielsv/CC-UGR/issues/21
https://github.com/jdanielsv/CC-UGR/issues/20
https://github.com/jdanielsv/CC-UGR/issues/19
https://github.com/jdanielsv/CC-UGR/issues/18
https://github.com/jdanielsv/CC-UGR/issues/17
https://github.com/jdanielsv/CC-UGR/issues/16
https://github.com/jdanielsv/CC-UGR/milestone/6
> Added hito6

- objetivos/agm-gr.md
[https://github.com/JJ/CC-17-18/blob/master/objetivos/agm-gr.md](https://github.com/JJ/CC-17-18/blob/master/objetivos/agm-gr.md)
[https://github.com/AGM-GR/CloudComputing-Ejercicios/blob/master/Semana%2010-11-12-13-14-15.md](https://github.com/AGM-GR/CloudComputing-Ejercicios/blob/master/Semana%2010-11-12-13-14-15.md)
Actualización de los objetivos y los ejercicios correspondientes realizados.
> Actualización de los objetivos semanales

- objetivos/javierfrereq.md
[enlace](https://github.com/javierfrereq/CC-17-18/blob/master/objetivos/javierfrereq.md)
[X] He llevado a cabo las actividades correspondientes al objetivo y he entendido para qué sirve.
[X] He actualizado con la última versión del fichero de entrega y
> Entrega de objetivos

- proyecto/6.md
Corresponde al hito <6
https://github.com/lchousal/CC-17-18/blob/master/objetivos/lchousal.md
Entrega correspondiente al hito 6
https://github.com/lchousal/CC-proyecto/issues/19
https://github.com/lchousal/CC-proyecto/issues/20
https://github.com/lchousal/CC-proyecto/issues/21
> Entrega hito 6

- proyecto/6.md
Corresponde al Hito 6
[Enlace Objetivos](https://github.com/javierfrereq/CC-17-18/blob/master/objetivos/javierfrereq.md)
Despliegue de docker-compose Azure 
Documentación de instalación: [enlace](https://github.com/javierfrereq/MII_CC_Proyecto_MicroServicios/tree/master/compose).
[Proyecto](https://github.com/javierfrereq/MII_CC_Proyecto_MicroServicios).
[docker-compose](https://github.com/javierfrereq/MII_CC_Proyecto_MicroServicios/tree/master/contenedores).
[Aprender sobre docker-compose](https://github.com/javierfrereq/MII_CC_Proyecto_MicroServicios/issues/11)
[Realizar el Hito 6](https://github.com/javierfrereq/MII_CC_Proyecto_MicroServicios/is …
> Entrega del Hito 6 

- proyecto/6.md
Terminado el hito 6, creación del servicio web a desplegar y despliegue con docker-compose.
[https://github.com/AGM-GR/CloudComputing/issues/8](https://github.com/AGM-GR/CloudComputing/issues/8)
[https://github.com/AGM-GR/CloudComputing/issues/9](https://github.com/AGM-GR/CloudComputing/issues/9)
[https://github.com/AGM-GR/CloudComputing/milestone/8](https://github.com/AGM-GR/CloudComputing/milestone/8)
> Añadido enlace al hito 6

- proyecto/6.md
[Enlace a fichero de objetivos](https://github.com/JJ/CC-17-18/blob/master/objetivos/tonyESP.md)
La orquestación de la aplicación se ha realizado mediante docker-composer. Levantando una maquina con node y otra con mongodb. Ambas imágenes son las oficiales para cada entorno. 
Podemos encontrar los detalles para su lanzamiento en azure en el siguiente [manual](https://github.com/tonyESP/MII_CC_Proyecto/blob/master/docker-compose/README.md).
https://github.com/tonyESP/MII_CC_Proyecto/issues/23
https://github.com/tonyESP/MII_CC_Proyecto/issues/22
https://github.com/tonyESP/MII_CC_Proyecto/issues/21 …
> hito 6 @tonyESP

- objetivos/AKourts.md
https://github.com/AKourts/CC-17-18/blob/master/objetivos/AKourts.md
Update the goals of the last three weeks
> update goals of last weeks

- proyecto/6.md
Hito 6, Docker Compose
https://github.com/AKourts/Project_CC/issues/12
https://github.com/AKourts/Project_CC/issues/11
> Deliver Hito 6

- proyecto/6.md
Corresponde al [Hito 6](https://github.com/RamonGago/Cloud-Computing_Project/milestone/6)
Se añade el Hito 6 de RamonGago.
Se han cerrado los siguientes issues, pertenecientes al milestone [Hito 6](https://github.com/RamonGago/Cloud-Computing_Project/milestone/6?closed=1):
- [#16](https://github.com/RamonGago/Cloud-Computing_Project/issues/16)
- [#17](https://github.com/RamonGago/Cloud-Computing_Project/issues/17)
- [#18](https://github.com/RamonGago/Cloud-Computing_Project/issues/18)
> Added Hito 6

- proyecto/6.md
correspondiente.   
Composicion de contenedores mongodb y nodejs para servir una web y una API REST
https://github.com/erseco/ugr_cloud_computing/issues/15
> Updated milestone 6
